import { CipherDetails, CipherSecurityStatus } from '../../../shared/types.ts';

export class CipherRegistry {
  private static readonly CIPHERS: Record<number, Omit<CipherDetails, 'id' | 'hexCode'>> = {
    // TLS 1.3 Ciphers
    0x1301: {
      name: 'TLS_AES_128_GCM_SHA256',
      standardName: 'TLS_AES_128_GCM_SHA256',
      protocol: 'TLSv1.3',
      keyExchange: 'ECDHE',
      auth: 'ANY',
      encryption: 'AES-128-GCM',
      keyLength: 128,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['Authenticated encryption (AEAD)', 'Perfect Forward Secrecy guaranteed in TLS 1.3'],
    },
    0x1302: {
      name: 'TLS_AES_256_GCM_SHA384',
      standardName: 'TLS_AES_256_GCM_SHA384',
      protocol: 'TLSv1.3',
      keyExchange: 'ECDHE',
      auth: 'ANY',
      encryption: 'AES-256-GCM',
      keyLength: 256,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['Strong 256-bit AEAD', 'Perfect Forward Secrecy guaranteed in TLS 1.3'],
    },
    0x1303: {
      name: 'TLS_CHACHA20_POLY1305_SHA256',
      standardName: 'TLS_CHACHA20_POLY1305_SHA256',
      protocol: 'TLSv1.3',
      keyExchange: 'ECDHE',
      auth: 'ANY',
      encryption: 'CHACHA20-POLY1305',
      keyLength: 256,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['High-performance AEAD', 'Perfect Forward Secrecy guaranteed in TLS 1.3'],
    },

    // TLS 1.2 ECDHE Secure
    0xc02f: {
      name: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
      standardName: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
      protocol: 'TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'RSA',
      encryption: 'AES-128-GCM',
      keyLength: 128,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['AEAD cipher', 'Elliptic Curve Diffie-Hellman Ephemeral (PFS)'],
    },
    0xc030: {
      name: 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
      standardName: 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
      protocol: 'TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'RSA',
      encryption: 'AES-256-GCM',
      keyLength: 256,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['Strong 256-bit AEAD', 'Elliptic Curve Diffie-Hellman Ephemeral (PFS)'],
    },
    0xcca8: {
      name: 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256',
      standardName: 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256',
      protocol: 'TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'RSA',
      encryption: 'CHACHA20-POLY1305',
      keyLength: 256,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['ChaCha20-Poly1305 AEAD', 'PFS supported'],
    },
    0xc02b: {
      name: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
      standardName: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
      protocol: 'TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'ECDSA',
      encryption: 'AES-128-GCM',
      keyLength: 128,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['AEAD cipher', 'ECDSA authentication', 'PFS supported'],
    },
    0xc02c: {
      name: 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
      standardName: 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
      protocol: 'TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'ECDSA',
      encryption: 'AES-256-GCM',
      keyLength: 256,
      mac: 'AEAD',
      pfs: true,
      securityStatus: 'SECURE',
      reasons: ['256-bit AEAD cipher', 'ECDSA authentication', 'PFS supported'],
    },

    // Acceptable CBC with PFS
    0xc013: {
      name: 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA',
      standardName: 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA',
      protocol: 'TLSv1.0 - TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'RSA',
      encryption: 'AES-128-CBC',
      keyLength: 128,
      mac: 'SHA1',
      pfs: true,
      securityStatus: 'ACCEPTABLE',
      reasons: ['Has PFS', 'Uses legacy CBC mode and SHA-1 MAC'],
    },
    0xc014: {
      name: 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA',
      standardName: 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA',
      protocol: 'TLSv1.0 - TLSv1.2',
      keyExchange: 'ECDHE',
      auth: 'RSA',
      encryption: 'AES-256-CBC',
      keyLength: 256,
      mac: 'SHA1',
      pfs: true,
      securityStatus: 'ACCEPTABLE',
      reasons: ['Has PFS', 'Uses legacy CBC mode and SHA-1 MAC'],
    },

    // Static RSA without PFS (WEAK)
    0x009c: {
      name: 'TLS_RSA_WITH_AES_128_GCM_SHA256',
      standardName: 'TLS_RSA_WITH_AES_128_GCM_SHA256',
      protocol: 'TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'AES-128-GCM',
      keyLength: 128,
      mac: 'AEAD',
      pfs: false,
      securityStatus: 'WEAK',
      reasons: ['Lacks Forward Secrecy (Static RSA key exchange)'],
    },
    0x009d: {
      name: 'TLS_RSA_WITH_AES_256_GCM_SHA384',
      standardName: 'TLS_RSA_WITH_AES_256_GCM_SHA384',
      protocol: 'TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'AES-256-GCM',
      keyLength: 256,
      mac: 'AEAD',
      pfs: false,
      securityStatus: 'WEAK',
      reasons: ['Lacks Forward Secrecy (Static RSA key exchange)'],
    },
    0x002f: {
      name: 'TLS_RSA_WITH_AES_128_CBC_SHA',
      standardName: 'TLS_RSA_WITH_AES_128_CBC_SHA',
      protocol: 'TLSv1.0 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'AES-128-CBC',
      keyLength: 128,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'WEAK',
      reasons: ['Lacks Forward Secrecy', 'Uses CBC mode', 'Uses SHA-1 HMAC'],
    },
    0x0035: {
      name: 'TLS_RSA_WITH_AES_256_CBC_SHA',
      standardName: 'TLS_RSA_WITH_AES_256_CBC_SHA',
      protocol: 'TLSv1.0 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'AES-256-CBC',
      keyLength: 256,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'WEAK',
      reasons: ['Lacks Forward Secrecy', 'Uses CBC mode', 'Uses SHA-1 HMAC'],
    },

    // Insecure & Broken Ciphers (3DES, RC4, DES, NULL)
    0x000a: {
      name: 'TLS_RSA_WITH_3DES_EDE_CBC_SHA',
      standardName: 'SSL_RSA_WITH_3DES_EDE_CBC_SHA',
      protocol: 'SSLv3 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: '3DES-EDE-CBC',
      keyLength: 112,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'INSECURE',
      reasons: [
        'Vulnerable to Sweet32 birthday attack (64-bit block size)',
        'Lacks Forward Secrecy',
        'Effective key length only 112 bits',
      ],
    },
    0x0004: {
      name: 'TLS_RSA_WITH_RC4_128_MD5',
      standardName: 'SSL_RSA_WITH_RC4_128_MD5',
      protocol: 'SSLv3 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'RC4-128',
      keyLength: 128,
      mac: 'MD5',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: [
        'RC4 stream cipher is cryptographically broken (RFC 7465 prohibited)',
        'MD5 hash is cryptographically broken',
        'Lacks Forward Secrecy',
      ],
    },
    0x0005: {
      name: 'TLS_RSA_WITH_RC4_128_SHA',
      standardName: 'SSL_RSA_WITH_RC4_128_SHA',
      protocol: 'SSLv3 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'RC4-128',
      keyLength: 128,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: [
        'RC4 stream cipher is cryptographically broken (RFC 7465 prohibited)',
        'Biased keystream bytes allow plaintext recovery',
        'Lacks Forward Secrecy',
      ],
    },
    0x0001: {
      name: 'TLS_RSA_WITH_NULL_MD5',
      standardName: 'SSL_RSA_WITH_NULL_MD5',
      protocol: 'SSLv3 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'NULL',
      keyLength: 0,
      mac: 'MD5',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: ['No encryption (NULL cipher: plaintext wire transmission)'],
    },
    0x0002: {
      name: 'TLS_RSA_WITH_NULL_SHA',
      standardName: 'SSL_RSA_WITH_NULL_SHA',
      protocol: 'SSLv3 - TLSv1.2',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'NULL',
      keyLength: 0,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: ['No encryption (NULL cipher: plaintext wire transmission)'],
    },
    0x0009: {
      name: 'TLS_RSA_WITH_DES_CBC_SHA',
      standardName: 'SSL_RSA_WITH_DES_CBC_SHA',
      protocol: 'SSLv3 - TLSv1.1',
      keyExchange: 'RSA',
      auth: 'RSA',
      encryption: 'DES-CBC',
      keyLength: 56,
      mac: 'SHA1',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: ['DES has only 56-bit key length and can be brute-forced in hours'],
    },
    0x0003: {
      name: 'TLS_RSA_EXPORT_WITH_RC4_40_MD5',
      standardName: 'SSL_RSA_EXPORT_WITH_RC4_40_MD5',
      protocol: 'SSLv3 - TLSv1.0',
      keyExchange: 'RSA-EXPORT',
      auth: 'RSA',
      encryption: 'RC4-40',
      keyLength: 40,
      mac: 'MD5',
      pfs: false,
      securityStatus: 'BROKEN',
      reasons: ['Deprecated 1990s 40-bit export cipher, completely trivially crackable'],
    },
  };

  public static lookup(cipherCode: number): CipherDetails {
    const idHex = `0x${cipherCode.toString(16).padStart(4, '0')}`;
    const entry = this.CIPHERS[cipherCode];

    if (entry) {
      return {
        id: idHex,
        hexCode: cipherCode,
        ...entry,
      };
    }

    // Heuristics for unknown cipher codes
    const isEcdhe = (cipherCode & 0xc000) === 0xc000;
    return {
      id: idHex,
      hexCode: cipherCode,
      name: `UNKNOWN_CIPHER_${idHex}`,
      protocol: 'TLS',
      keyExchange: isEcdhe ? 'ECDHE' : 'UNKNOWN',
      auth: 'UNKNOWN',
      encryption: 'UNKNOWN',
      keyLength: 0,
      mac: 'UNKNOWN',
      pfs: isEcdhe,
      securityStatus: 'ACCEPTABLE',
      reasons: ['Unrecognized cipher suite code in IANA registry'],
    };
  }
}
